#!/bin/bash
set -euo pipefail

# Define variables.
: ${OSXR_BREW_FORCE_INSTALL:=0}

# Install packages.
if ! brew update || [ "${OSXR_BREW_FORCE_INSTALL}" -eq 1 ] ;then
  brew install \
    aom \
    autoconf \
    automake \
    awscli \
    bash-completion \
    bat \
    bdw-gc \
    berkeley-db \
    brew-cask-completion \
    brotli \
    c-ares \
    cairo \
    chromedriver \
    coreutils \
    docker \
    e2fsprogs \
    editorconfig \
    exercism \
    fd \
    fetch \
    ffmpeg \
    flac \
    fontconfig \
    freetds \
    freetype \
    frei0r \
    fribidi \
    gd \
    gdbm \
    gdk-pixbuf \
    geckodriver \
    gettext \
    ghostscript \
    giflib \
    git \
    git-extras \
    git-gui \
    gitui \
    glib \
    glooctl \
    gmp \
    gnu-getopt \
    gnupg \
    gnutls \
    go \
    gobject-introspection \
    golangci-lint \
    graphite2 \
    graphviz \
    gts \
    guile \
    harfbuzz \
    helm \
    helmfile \
    htop \
    hub \
    hugo \
    icu4c \
    ilmbase \
    imagemagick \
    imath \
    jansson \
    jasper \
    jbig2dec \
    jemalloc \
    jenv \
    jpeg \
    jq \
    krb5 \
    kubernetes-cli \
    kubernetes-helm \
    lame \
    leptonica \
    libass \
    libassuan \
    libbluray \
    libde265 \
    libev \
    libevent \
    libffi \
    libgcrypt \
    libgpg-error \
    libheif \
    libidn \
    libidn2 \
    libksba \
    liblqr \
    libmaxminddb \
    libogg \
    libomp \
    libpng \
    libpq \
    libpthread-stubs \
    librsvg \
    libsamplerate \
    libsmi \
    libsndfile \
    libsodium \
    libsoxr \
    libssh \
    libssh2 \
    libtasn1 \
    libtiff \
    libtool \
    libunistring \
    libusb \
    libuv \
    libvidstab \
    libvorbis \
    libvpx \
    libx11 \
    libxau \
    libxcb \
    libxdmcp \
    libxext \
    libxrender \
    libyaml \
    little-cms2 \
    lsd \
    lua \
    lua@5.1 \
    lzo \
    m4 \
    macos-term-size \
    makedepend \
    minikube \
    miniserve \
    most \
    mpdecimal \
    multitail \
    mycli \
    ncurses \
    netcat \
    netpbm \
    nettle \
    nghttp2 \
    node \
    node@12 \
    npth \
    nushell \
    oniguruma \
    opencore-amr \
    openexr \
    openjdk \
    openjpeg \
    openssl@1.1 \
    optipng \
    opus \
    osmfilter \
    osmosis \
    p11-kit \
    p7zip \
    pandoc \
    pango \
    pcre \
    pcre2 \
    perl \
    pgcli \
    pinentry \
    pip-completion \
    pixman \
    pkg-config \
    poetry \
    postgresql \
    pyenv \
    python \
    python-tabulate \
    python3 \
    python@3.9 \
    rav1e \
    readline \
    redis \
    ripgrep \
    rtmpdump \
    rubberband \
    ruby \
    rustup-init \
    s-lang \
    sbcl \
    sdl2 \
    shared-mime-info \
    shellcheck \
    skaffold \
    snappy \
    speex \
    sqlite \
    srt \
    starship \
    tcl-tk \
    tektoncd-cli \
    terraform \
    terraformer \
    tesseract \
    theora \
    tree \
    unbound \
    unixodbc \
    vagrant-completion \
    vault \
    webp \
    wget \
    wireshark \
    x264 \
    x265 \
    xmlto \
    xorgproto \
    xsv \
    xvid \
    xz \
    yarn \
    zeromq \
    zimg \
    zlib 

  
  # Install cask formulas.
  brew install --cask \
    android-platform-tools \
    android-sdk \
    android-studio \
    angry-ip-scanner \
    brave-browser \
    chromedriver \
    dbeaver-community \
    deluge \
    dropbox \
    firefox \
    flux \
    freecad \
    gimp \
    google-chrome \
    iterm2 \
    krita \
    libreoffice \
    mu-editor \
    ngrok \
    postman \
    rar \
    rectangle \
    sketchup \
    skype \
    slack \
    sweet-home3d \
    the-battle-for-wesnoth \
    time-out \
    vagrant \
    virtualbox \
    visual-studio-code \
    vlc \
    xquartz


  # Clean up.
  brew cleanup
fi

