
# Setup Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"

# Setup Starship prompt
eval "$(starship init bash)"

# Use Bash completion, if installed.
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi

# Use Bash aliases, if any.
[ -f ~/.bash_aliases ] && . ~/.bash_aliases

# Use Bash functions, if any.
[ -f ~/.bash_functions ] && . ~/.bash_functions

# Use secrets if any (i.e. Github tokens).
[ -f ~/.bash_secrets ] && . ~/.bash_secrets

# Use specific variables for custom projects.
[ -f ~/.bash_projects ] && . ~/.bash_projects

# Use pyenv.
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# Use Python 3.12
export PATH="$(brew --prefix)/opt/python@3.12/bin:$PATH"

# Set Go variables.
if go version >/dev/null 2>&1; then
  export GOPATH=$(go env GOPATH)
  export PATH=$PATH:$(go env GOPATH)/bin
fi

# GitHub variables.
export GITHUB_USER="rgreinho"
export GITSIGN_CONNECTOR_ID="https://github.com/login/oauth"

# Silence OSX Bash deprecation warning.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Use Rust.
[ -f  "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
# Enable cargo's sparse protocol.
export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse

export PKG_CONFIG_PATH="$(brew --prefix)/opt/openssl@3/lib/pkgconfig"
export PATH="/opt/local/bin:$PATH"
export PATH="$(brew --prefix)/opt/openssl@3/bin:$PATH"

# NVM.
export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" # This loads nvm
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" # This loads nvm bash_completion
