# Use the system config if it exists.
[ -f /etc/bashrc ] && . /etc/bashrc

# Use local Bash config if any.
[ -f ~/.bashrc ] && . ~/.bashrc

# Use Bash completion, if installed.
if type brew &>/dev/null; then
  HOMEBREW_PREFIX="$(brew --prefix)"
  if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
    source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
  else
    for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
      [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
  fi
fi

# Use Bash aliases, if any.
[ -f ~/.bash_aliases ] && . ~/.bash_aliases

# Use Bash functions, if any.
[ -f ~/.bash_functions ] && . ~/.bash_functions

# Use secrets if any (i.e. Github tokens).
[ -f ~/.bash_secrets ] && . ~/.bash_secrets

# Use specific variables for custom projects.
[ -f ~/.bash_projects ] && . ~/.bash_projects

# Use Liquid Prompt.
# export LP_PATH_LENGTH=20
# Load liquidprompt either from brew either from src.
# if [ -f /usr/local/share/liquidprompt ]; then
#   . /usr/local/share/liquidprompt
# else
#  [-f /usr/local/src/liquidprompt/liquidprompt ] && . /usr/local/src/liquidprompt/liquidprompt
# fi
# If you have your own config for Liquid Prompt, edit and uncomment this line:
# source /path/to/liquidpromptrc

# Use virtualenv wrapper.
# export VIRTUALENVWRAPPER_PYTHON=$(which python3)
# export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
# [ -f /usr/local/bin/virtualenvwrapper_lazy.sh ] && . /usr/local/bin/virtualenvwrapper_lazy.sh

# Use pyenv.
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi

# Set Go variables.
if go version >/dev/null 2>&1; then
  export GOPATH=$(go env GOPATH)
  export PATH=$PATH:$(go env GOPATH)/bin
fi

# GitHub variables.
export GITHUB_USER="rgreinho"
# export GITHUB_ORGANIZATION="request-yo-racks"

# Silence OSX Bash deprecation warning.
export BASH_SILENCE_DEPRECATION_WARNING=1

# BPython breakpoint
export PYTHONBREAKPOINT=bpdb.set_trace

# Use Node 12.
export PATH="/usr/local/opt/node@12/bin:$PATH"
# Use Ruby 2.6.
export PATH="/usr/local/opt/ruby/bin:$PATH"
# Python user site-packages.
export PATH=$PATH:$(python3 -m site --user-base)/bin
# Use Python 3.9.
export PATH="/usr/local/opt/python@3.9/bin:$PATH"
# Use Rust.
export PATH="$HOME/.cargo/bin:$PATH"
# Use Terraform 0.13.
export PATH="/usr/local/opt/terraform@0.13/bin:$PATH"

# Setup rvm.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

# Setup Android SDK.
if [ -d /usr/local/share/android-sdk  ]; then
    export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"
    export ANDROID_SDK="/Users/remy/Library/Android/sdk"
    export PATH="$ANDROID_SDK/platform-tools:$PATH"
fi

# Setup Starship prompt
eval "$(starship init bash)"
export PATH="/usr/local/sbin:$PATH"
