# Use the system config if it exists.
[ -f /etc/bashrc ] && . /etc/bashrc

# Use Bash completion, if installed.
[ -f /etc/bash_completion ]&& . /etc/bash_completion
[ -f $(brew --prefix)/etc/bash_completion ] && . $(brew --prefix)/etc/bash_completion
[ -d ~/.bash_completion.d ] && . ~/.bash_completion.d/*

# Use Bash aliases, if any.
[ -f ~/.bash_aliases ] && . ~/.bash_aliases

# Use Bash functions, if any.
[ -f ~/.bash_functions ] && . ~/.bash_functions

# Use secrets if any (i.e. Github tokens).
[ -f ~/.bash_secrets ] && . ~/.bash_secrets

# Use Liquid Prompt.
export LP_PATH_LENGTH=35
source /usr/local/src/liquidprompt/liquidprompt
# If you have your own config for Liquid Prompt, edit and uncomment this line:
# source /path/to/liquidpromptrc

# Use virtualenv.
export VIRTUALENVWRAPPER_PYTHON=$(which python3)
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
source /usr/local/bin/virtualenvwrapper_lazy.sh
